import Head from "next/head";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pizza App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <h3 className='text-3xl font-bold'>tailwind manzon</h3>
    </div>
  );
}
